---
http_client_port: 18027
http_public_port: 17027
udp_server_port: 16027
database: host=localhost port=5432 dbname=ubot_t27
node_number: 27
public_host: localhost
node_name: ubot_27
ip:
- 127.0.0.1
